#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd infrastructure

echo "Running terraform fmt..."
terraform fmt -check -recursive

echo "Running terraform validate..."
terraform init -backend=false
terraform validate

echo "Running tflint..."
tflint